import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'

const inter = Raleway({ subsets: ['latin'], weight: '400', style: 'italic' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`container`}>{children}</body>
    </html>
  )
}
